[mypy]
check_untyped_defs = False
ignore_missing_imports = True
files = slixmpp

[mypy-slixmpp.types]
ignore_errors = True

[mypy-slixmpp.thirdparty.*]
ignore_errors = True

[mypy-slixmpp.plugins.base]
ignore_errors = False

[mypy-slixmpp.plugins.xep_0004.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0009.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0012.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0013.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0027.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0030.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0045.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0047.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0049.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0050.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0054.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0059.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0060.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0084.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0100.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0115.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0152.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0153.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0163.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0199.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0202.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0223.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0231.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0249.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0264.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0300.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0308.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0313.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0319.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0363.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0369.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0377.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0385.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0404.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0410.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0421.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0424.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0425.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0428.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0439.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0441.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0446.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0449.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0454.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0455.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0462.*]
ignore_errors = True

[mypy-slixmpp.plugins.xep_0494.*]
ignore_errors = True
