[project]
name = "slixmpp"
dynamic = ["version"]
description = "Slixmpp is an elegant Python library for XMPP (aka Jabber)."
readme = "README.rst"
license = "MIT"
authors = [
    { name = "Florent Le Coz", email = "louiz@louiz.org" },
    { name = "Mathieu Pasquet (mathieui)", email = "mathieui@mathieui.net" },
    { name = "Emmanuel Gil Peyrot (Link Mauve)", email = "linkmauve@linkmauve.fr" },
    { name = "Maxime “pep” Buquet", email = "pep@bouah.org" },
]
maintainers = [
    { name = "Mathieu Pasquet (mathieui)", email = "mathieui@mathieui.net" },
    { name = "Emmanuel Gil Peyrot (Link Mauve)", email = "linkmauve@linkmauve.fr" },
    { name = "Maxime “pep” Buquet", email = "pep@bouah.org" },
]
requires-python = ">=3.11"
dependencies = [
    "aiodns>=3.2.0",
    "pyasn1>=0.6.1",
    "pyasn1-modules>=0.4.1",
]
classifiers = [
    'Intended Audience :: Developers',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3.14',
    'Topic :: Internet :: XMPP',
    'Topic :: Software Development :: Libraries :: Python Modules',
]

[project.optional-dependencies]
xep-0363 = ["aiohttp"]
xep-0444-compliance = ["emoji"]
xep-0454 = ["cryptography"]
safer-xml-parsing = ["defusedxml"]

[tool.uv]
cache-keys = [{file = "pyproject.toml"}, {file = "rust/Cargo.toml"}, {file = "**/*.rs"}]

[build-system]
requires = ["setuptools", "setuptools-rust", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[tool.setuptools]

[tool.setuptools.packages.find]
include = ["slixmpp*"]
exclude = ["itests", "tests"]
namespaces = false

[tool.setuptools_scm]

[[tool.setuptools-rust.ext-modules]]
target = "slixmpp.jid"
optional = true

[dependency-groups]
lint = [
    "mypy>=1.14.1",
    "typos>=1.39.2",
]

docs = [
    "sphinx",
    "sphinx-autodoc-typehints",
    "furo"
]
