when:
  - event: [ manual ]
  - event: push
    path: [ "Containerfile" ]
    branch: master
  - event: cron
    cron: containers

labels:
  platform: linux/amd64

steps:
  ci:
    image: woodpeckerci/plugin-docker-buildx:6.0.2
    depends_on: []
    settings:
      platforms: linux/amd64,linux/arm64
      target: ci
      tag: ci
      registry: codeberg.org
      username: nicoco
      dockerfile: Containerfile
      repo: codeberg.org/poezio/slixmpp
      password:
        from_secret: codeberg_package_nicoco

  prosody:
    image: woodpeckerci/plugin-docker-buildx:6.0.2
    depends_on: []
    settings:
      repo: codeberg.org/poezio/slixmpp
      platforms: linux/amd64,linux/arm64
      target: prosody
      tag: prosody
      registry: codeberg.org
      username: nicoco
      dockerfile: Containerfile
      password:
        from_secret: codeberg_package_nicoco
