when:
  event: [ push, pull_request ]
  path: [ "**/*.py", "uv.lock", ".woodpecker/lint.yml" ]

steps:
  setup_venv:
    image: codeberg.org/poezio/slixmpp:ci
    pull: true
    commands:
    - uv sync --frozen --only-group dev
  mypy:
    image: codeberg.org/poezio/slixmpp:ci
    commands:
    - mypy slixmpp
  typos:
    image: codeberg.org/poezio/slixmpp:ci
    commands:
    - typos
