when:
  event: [ push, pull_request ]
  path: [ "**/*.py", "uv.lock", "Cargo.toml", ".woodpecker/test.yml", "**/*.rs"  ]

steps:
  setup_venv:
    image: codeberg.org/poezio/slixmpp:ci
    commands:
    - uv python pin ${TAG}
    - uv sync --frozen --all-groups --all-extras
  unit_tests:
    image: codeberg.org/poezio/slixmpp:ci
    commands:
    - ./run_tests.py

matrix:
  TAG:
    - "3.11"
    - "3.12"
    - "3.13"
    - "3.14"
