when:
  event: [ push, pull_request ]

steps:
  unit_tests:
    image: "python:${TAG}"
    commands:
    - apt-get update
    - apt-get install -y python3 python3-pip cython3 gpg
    - pip3 install emoji aiohttp cryptography setuptools
    - ./run_tests.py

matrix:
  TAG:
    - "3.9"
    - "3.10"
    - "3.11"
    - "3.12"
    - "3.13"
